robot_grippers:
  - {vacuum_gripper: 'right arm'}
  - {claw_gripper: 'left arm'}

world_positions:
  # TO DO: define exact positions
  {'name': 'A', 'center': '[0.20,0.25,0.25]', 'dims_in_meters': '[0.05,0.05,0.001]'}
#  - {'name': 'A', 'center': '[0.20,0.25,0.25]', 'dims_in_meters': '[0.05,0.05,0.001]'}
#  - {'name': 'B', 'center': '[0.20,0.25,0.25]', 'dims_in_meters': '[0.05,0.05,0.001]'}
#  - {'name': 'C', 'center': '[0.20,0.25,0.25]', 'dims_in_meters': '[0.05,0.05,0.001]'}
#  - {'name': 'D', 'center': '[0.20,0.25,0.25]', 'dims_in_meters': '[0.05,0.05,0.001]'}

world_objects:
  # Table object dimension ratio
  - {'name': 'cube', 'dims_ratio': '[1.0,1.0,1.0]'}
  - {'name': 'rectangle', 'dims_ratio': '[1.0,1.0,2.0]'}
  - {'name': 'plate', 'dims_ratio': '[1.0,1.0,0.25]'}
  - {'name': 'tower', 'dims_ratio': '[1.0,1.0,3.0]'}
